services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - VITE_API_URL=http://server:3001

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
