services:
  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - VITE_API_URL=http://server:3001

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_MAX=${POSTGRES_MAX}
      - POSTGRES_MIN=${POSTGRES_MAX}
      - POSTGRES_IDLE_TIMEOUT=${POSTGRES_MAX}

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
